### ISSUE TITLE
How to run the jobs on gpu?

### ISSUE THREAD

**Issue by luisegehaijing** [dimonenka/RL_policy_budget#2]
Hello, I have changed all the device to "cuda" instead of "cpu".

However, I still keep getting errors like this:

Traceback (most recent call last):
  File "/home/research/g.luise/multi_policy2024/personalisation/RL_policy_budget-main/main_ray.py", line 31, in <module>
    ray.get(result_ids)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::run_ray()[39m (pid=1506632, ip=10.24.77.16)
  File "/home/research/g.luise/multi_policy2024/personalisation/RL_policy_budget-main/main_ray.py", line 14, in run_ray
    run_gym(env_name, algorithm, cfg, seed, n_agents, n_policies, base_reward=False, device='cuda')
  File "/home/research/g.luise/multi_policy2024/personalisation/RL_policy_budget-main/core/main.py", line 86, in run_gym
    policy.train()
  File "/home/research/g.luise/multi_policy2024/personalisation/RL_policy_budget-main/policy.py", line 307, in train
    self.warm_start()
  File "/home/research/g.luise/multi_policy2024/personalisation/RL_policy_budget-main/policy.py", line 163, in warm_start
    self.M_step()
  File "/home/research/g.luise/multi_policy2024/personalisation/RL_policy_budget-main/policy.py", line 263, in M_step
    _, new_log_prob_batch, entropy_batch = self.policy(state_batch, action_batch)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/research/g.luise/multi_policy2024/personalisation/RL_policy_budget-main/utils/networks.py", line 71, in forward
    mu = self.fc(x)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/research/g.luise/miniconda3/envs/budget/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

Do you know how to set it up properly?

**Comment by dimonenka** [comment]
Hi, notice that in main_ray.py "device='cpu'" and "num_gpus=0" -- this file is intended for parallel experiments on several cpus. If you want to parallel on gpus, you should set "device='cuda'" and "num_gpus=number_of_gpus_you_have / number_of_parallel_tasks_you_run". If you want to run one task on gpu, you should run core/main.py -- adjust details at the bottom of the file under "if name == main".

**Comment by luisegehaijing** [comment]
Hi, I have done that. But there are still these errors.
